/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cliente;

/**
 *
 * @author Alberto Berenguer
 */
public class InterfazChat extends javax.swing.JFrame {
    ChatCliente chat;
    /**
     * Creates new form InterfazChat
     */
    public InterfazChat() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        areaMensajes = new javax.swing.JTextArea();
        baudio = new javax.swing.JButton();
        tusuario = new javax.swing.JLabel();
        eusuario = new javax.swing.JTextField();
        tservidor = new javax.swing.JLabel();
        eservidor = new javax.swing.JTextField();
        epuerto = new javax.swing.JTextField();
        tpuerto = new javax.swing.JLabel();
        bConectar = new javax.swing.JButton();
        bDesconectar = new javax.swing.JButton();
        fondo = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lista = new javax.swing.JList<>();
        emensaje = new javax.swing.JTextField();
        bfoto = new javax.swing.JButton();
        benviar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CHAT CS");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        areaMensajes.setColumns(20);
        areaMensajes.setRows(5);
        jScrollPane2.setViewportView(areaMensajes);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 822, 350));

        baudio.setText("Audio");
        getContentPane().add(baudio, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 430, -1, -1));

        tusuario.setText("Usuario :");
        getContentPane().add(tusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, -1, -1));
        getContentPane().add(eusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 122, -1));

        tservidor.setText("IP Servidor :");
        getContentPane().add(tservidor, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, -1, -1));
        getContentPane().add(eservidor, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, 120, -1));

        epuerto.setText("8880");
        getContentPane().add(epuerto, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 20, 71, -1));

        tpuerto.setText("Puerto :");
        getContentPane().add(tpuerto, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 20, -1, -1));

        bConectar.setText("Conectar");
        bConectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bConectarActionPerformed(evt);
            }
        });
        getContentPane().add(bConectar, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 20, 100, -1));

        bDesconectar.setText("Desconectar");
        getContentPane().add(bDesconectar, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 20, -1, -1));

        fondo.setBackground(new java.awt.Color(51, 204, 255));
        fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lista.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lista);

        fondo.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 160, 350));

        emensaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emensajeActionPerformed(evt);
            }
        });
        fondo.add(emensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 430, 619, -1));

        bfoto.setText("Foto");
        fondo.add(bfoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 430, -1, -1));

        benviar.setText("Enviar");
        fondo.add(benviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 430, -1, -1));

        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emensajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emensajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emensajeActionPerformed

    private void bConectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bConectarActionPerformed
         
    }//GEN-LAST:event_bConectarActionPerformed

    /**
     * @param args the command line arguments
     */
    public void enableConnected() {
        eservidor.setEditable(false);
        eservidor.setEnabled(false);
        epuerto.setEditable(false);
        epuerto.setEnabled(false);
        eusuario.setEditable(false);
        eusuario.setEnabled(false);
        emensaje.setEnabled(true);
        benviar.setEnabled(true);
        bConectar.setEnabled(false);
        bDesconectar.setEnabled(true);
    }

    public void enableDisconnected() {
        eservidor.setText(null);
        eservidor.setEditable(true);
        eservidor.setEnabled(true);
        epuerto.setText(null);
        epuerto.setEditable(true);
        epuerto.setEnabled(true);
        eusuario.setText(null);
        eusuario.setEditable(true);
        eusuario.setEnabled(true);
        emensaje.setEnabled(false);
        benviar.setEnabled(false);
        bConectar.setEnabled(true);
        bDesconectar.setEnabled(false);
    }

    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazChat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaMensajes;
    private javax.swing.JButton bConectar;
    private javax.swing.JButton bDesconectar;
    private javax.swing.JButton baudio;
    private javax.swing.JButton benviar;
    private javax.swing.JButton bfoto;
    private javax.swing.JTextField emensaje;
    private javax.swing.JTextField epuerto;
    private javax.swing.JTextField eservidor;
    private javax.swing.JTextField eusuario;
    private javax.swing.JPanel fondo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> lista;
    private javax.swing.JLabel tpuerto;
    private javax.swing.JLabel tservidor;
    private javax.swing.JLabel tusuario;
    // End of variables declaration//GEN-END:variables
}
